@startuml useCase
left to right direction

actor "Visiteur" as fc0

actor "Chauffeur" as fc1
actor "Passager" as fc2


fc0 <|--- fc1
fc0 <|--- fc2






rectangle system {
    
    usecase "Voir les Trajets" as UC1

    usecase "Ajouter une Trajet" as MUC1
    usecase "Modifierer ses Trajets" as MUC2
    usecase "Suprimer ses Trajets" as MUC3

    usecase "Contacter Chauffeur" as NMUC1
    usecase "Ajouter Review" as NMUC2

    

    (MUC1) ..> (s'authentifier) : include
    (MUC2) ..> (s'authentifier) : include
    (MUC3) ..> (s'authentifier) : include

    (NMUC1) ...> (s'authentifier) : include
    (NMUC2) ...> (s'authentifier) : include
}


fc0 -left- UC1


fc1 -- MUC1
fc1 -- MUC2
fc1 --- MUC3

fc2 --- NMUC1
fc2 --- NMUC2


@enduml